LABELS = { 
	"DIV": "Divorce",
	"SAPCR": "Original SAPCR",
	"MODS": "Modify Child Support",
	"MODP": "Modify Parenting Plan",
	"ENFS": "Enforce Child Support",
	"ENFP": "Enforce Parenting Plan",
	"ENFD": "Enforce Property Division",
	"ADOP": "Adoption",
	"TERM": "Termination",
	"FVPO": "Protective Order",
	"EMAN": "Emancipation of Minor",
	"ANNU": "Annulment",
	"Nonex": "None",
	"MENU": "Show Menu",
	"IDENTIFY": "Identify",
	"PROF": "Show Profile",
	"ANSW": "Original Answer",
	"QDRO": "QDRO",
	"RELOAD": "Reload Profile"
}